#!/usr/bin/env bash
# Bash Script that transfer a file to  a server from client

if (("$#" < 3))
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
